# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: f124ddd161b19ce72fdb0c6e30f3efc7b2f00d7baa852369688b48678496397ce8b3ae9a09802b21adeaa7c7559da82c2f33a124e47677326a3c1b2d85132d20

test:
  domain_name: example.com 
  secret_key_base: 039900902792505af002052f2eb9584a79dd966cff8c4455b044515bf4f9d2fecf9376c836a49d1ab5c2d9065a9eac5f53be0a85930ea7f71b4446bc632812fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: http://www.heretodayart.com/
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
